Repository KBKN-Autonomous-Robotics-Lab/orange_ros2, pull requests merged in 2023-05, with the labels that each got.

#31 ros2bagのバグ取りによるREADme内のデータセットの更新
  README.md
Labels: bug

#29 Feature/urg node
  orange_bringup/launch/orange_robot.launch.xml
  orange_bringup/package.xml
Labels: enhancement, task

#32 fix joycon node
  orange_teleop/config/elecom.yaml
  orange_teleop/launch/teleop_joy.launch.xml
  orange_teleop/package.xml
Labels: enhancement

#33 Feature/fusion scan
  orange_bringup/launch/orange_robot.launch.xml
Labels: enhancement, task

#34 Feature/add velodyne param
  orange_bringup/launch/orange_robot.launch.xml
Labels: enhancement, task
