Repository KBKN-Autonomous-Robotics-Lab/orange_ros2, pull requests merged in 2023-01, with the labels that each got.

#5 Fix launch format and add ros2 bag support to orange_slam
  README.md
  orange_bringup/launch/rviz2.launch.py
  orange_bringup/launch/rviz2.launch.xml
  orange_bringup/package.xml
  orange_description/package.xml
  orange_description/rviz2/orange_robot.rviz
  orange_description/rviz2/slam_toolbox.rviz
  orange_description/xacro/sensors/hokuyo.xacro
  orange_description/xacro/sensors/imu.xacro
  orange_description/xacro/sensors/velodyne.xacro
  orange_gazebo/launch/empty_world.launch.py
  orange_gazebo/launch/empty_world.launch.xml
  orange_gazebo/launch/orange_igvc.launch.py
  orange_gazebo/launch/orange_igvc.launch.xml
  orange_gazebo/launch/orange_world.launch.py
  orange_gazebo/launch/orange_world.launch.xml
  orange_gazebo/package.xml
  orange_sensor_tools/config/ekf_node.yaml
  orange_sensor_tools/launch/localization.launch.py
  orange_sensor_tools/launch/localization.launch.xml
  orange_sensor_tools/launch/pointcloud_to_laserscan.launch.py
  orange_sensor_tools/launch/pointcloud_to_laserscan.launch.xml
  orange_sensor_tools/package.xml
  orange_slam/config/offline_slam_toolbox_params.yaml
  orange_slam/config/online_slam_toolbox_params.yaml
  orange_slam/launch/slam_toolbox.launch.py
  orange_slam/launch/slam_toolbox.launch.xml
  orange_slam/package.xml
  orange_teleop/launch/teleop_joy.launch.py
  orange_teleop/launch/teleop_joy.launch.xml
  orange_teleop/launch/teleop_keyboard.launch.py
  orange_teleop/launch/teleop_keyboard.launch.xml
  orange_teleop/package.xml
  orange_teleop/setup.py
Labels: enhancement, task

#7 add texture to igvc world
  orange_gazebo/models/orange_igvc/model.sdf
Labels: task

#8 Fix/version
  README.md
  orange_bringup/package.xml
  orange_description/package.xml
  orange_gazebo/package.xml
  orange_sensor_tools/package.xml
  orange_slam/package.xml
  orange_teleop/package.xml
  orange_teleop/setup.py
Labels: documentation
