Repository KBKN-Autonomous-Robotics-Lab/orange_ros2, pull requests merged in 2023-11, with the labels that each got.

#73 Fix/nav2 local costmap
  orange_navigation/config/navigation2_params.yaml
Labels: enhancement

#75 fix_nav2_param
  orange_navigation/config/navigation2_params.yaml
Labels: enhancement

#76 Fix/velocity increase
  orange_bringup/config/motor_driver_params.yaml
  orange_navigation/config/navigation2_params.yaml
Labels: enhancement

#77 fix/velocity_smoother_odom_topic
  orange_navigation/config/navigation2_params.yaml
Labels: bug

#78 Feature/ground segmentation
  orange_bringup/launch/orange_robot.launch.xml
  orange_bringup/launch/with_ros2bag.launch.xml
  orange_gazebo/launch/empty_world.launch.xml
  orange_gazebo/launch/orange_hosei.launch.xml
  orange_gazebo/launch/orange_igvc.launch.xml
  orange_gazebo/launch/orange_world.launch.xml
  orange_ros2.rosinstall
  orange_sensor_tools/config/ground_segmentation.yaml
  orange_sensor_tools/launch/ground_segmentation.launch.xml
  orange_sensor_tools/package.xml
Labels: enhancement

#80 fix_local_costmap_global_frame
  orange_navigation/config/navigation2_params.yaml
Labels: bug

#81 fix_inflation_radius
  orange_navigation/config/navigation2_params.yaml
Labels: bug, enhancement

#82 Fix/nav2 param navigation
  orange_navigation/config/navigation2_params.yaml
  orange_navigation/launch/multi_map_navigation.launch.xml
  orange_navigation/launch/waypoint_navigation.launch.xml
Labels: bug

#83 Fix/tsukuba navigation
  orange_navigation/config/navigation2_params_from_left.yaml
  orange_navigation/config/navigation2_params_from_right.yaml
  orange_navigation/launch/multi_map_navigation.launch.xml
  orange_navigation/launch/waypoint_navigation.launch.xml
Labels: bug, enhancement

#84 add_timeout_restart_nav_param
  orange_navigation/launch/multi_map_navigation.launch.xml
  orange_navigation/launch/waypoint_navigation.launch.xml
Labels: enhancement
