Repository KBKN-Autonomous-Robotics-Lab/orange_ros2, pull requests merged in 2023-07, with the labels that each got.

#41 fix_change_IMUnode_to_IMUinclude
  orange_bringup/launch/orange_robot.launch.xml
Labels: bug

#44 add timeout to spin_once
  orange_bringup/orange_bringup/motor_driver_node.py
Labels: bug

#45 fix_motor_param
  orange_bringup/config/motor_driver_params.yaml
Labels: enhancement, task

#56 fix params for dualsense
  orange_bringup/config/motor_driver_params.yaml
  orange_teleop/config/dualsense.yaml
  orange_teleop/config/elecom.yaml
  orange_teleop/launch/teleop_joy.launch.xml
Labels: enhancement

#55 fix_quaternion
  orange_bringup/orange_bringup/motor_driver_node.py
Labels: bug

#59 Feature/robot localization
  orange_sensor_tools/config/ekf_node.yaml
Labels: bug, enhancement, task

#60 fix_scale_angular
  orange_teleop/config/dualsense.yaml
Labels: bug
